services:
  postgres:
    image: postgres:16
    container_name: shop-postgres
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop -d shopdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # evita che Spring provi a gestire compose da solo
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
    ports:
      - "8080:8080"

volumes:
  pgdata:
